server:
  port: 8082

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-central-1}
      credentials:
        use-default-aws-credential-chain: true

app:
  hotel-service-url: ${HOTEL_SERVICE_BASE_URL:http://localhost:8080}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
