#!/bin/bash
set -e

###############################################################################
# Hotel Booking System — AWS Infrastructure Setup Script
# Region: eu-central-1
###############################################################################

REGION="eu-central-1"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
TIMESTAMP=$(date +%s)
UNIQUE_SUFFIX="${TIMESTAMP: -6}"
ENV_FILE="$(dirname "$0")/.env.generated"
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Set your Anthropic API key before running (or export it in your shell)
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:?Error: ANTHROPIC_API_KEY environment variable is not set}"

# DB credentials
DB_PASSWORD="H0tel$(openssl rand -hex 8)Secure!"
DB_USERNAME="hoteluser"
DB_NAME="hoteldb"

log() { echo "[$(date '+%H:%M:%S')] $*"; }

log "Starting Hotel Booking System AWS setup..."
log "Account: $ACCOUNT_ID | Region: $REGION | Suffix: $UNIQUE_SUFFIX"

# Initialize .env.generated
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
AWS_ACCOUNT_ID=$ACCOUNT_ID
AWS_REGION=$REGION
UNIQUE_SUFFIX=$UNIQUE_SUFFIX
EOF

###############################################################################
# 1. ECR Repositories
###############################################################################
log "Creating ECR repositories..."
SERVICES=("hotel-service" "comments-service" "notification-service" "ai-agent-service" "api-gateway" "frontend")

for SVC in "${SERVICES[@]}"; do
    aws ecr describe-repositories --repository-names "$SVC" --region $REGION 2>/dev/null || \
    aws ecr create-repository --repository-name "$SVC" --region $REGION --output json
    log "  ECR: $SVC"
done

ECR_BASE="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
echo "ECR_BASE=$ECR_BASE" >> "$ENV_FILE"

###############################################################################
# 2. ECR Login and Docker Build/Push
###############################################################################
log "Logging into ECR..."
aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_BASE

BACKEND_SERVICES=("hotel-service" "comments-service" "notification-service" "ai-agent-service" "api-gateway")
for SVC in "${BACKEND_SERVICES[@]}"; do
    SVC_DIR="$SCRIPT_DIR/$SVC"
    if [ -d "$SVC_DIR" ]; then
        log "Building and pushing $SVC..."
        docker build -t "$SVC:latest" "$SVC_DIR" --platform linux/amd64
        docker tag "$SVC:latest" "$ECR_BASE/$SVC:latest"
        docker push "$ECR_BASE/$SVC:latest"
    else
        log "WARNING: $SVC_DIR not found, skipping build"
    fi
done

###############################################################################
# 3. Cognito User Pool
###############################################################################
log "Creating Cognito User Pool..."
USER_POOL_JSON=$(aws cognito-idp create-user-pool \
    --pool-name hotel-booking-pool \
    --policies '{"PasswordPolicy":{"MinimumLength":8,"RequireUppercase":true,"RequireLowercase":true,"RequireNumbers":true,"RequireSymbols":false}}' \
    --auto-verified-attributes email \
    --username-attributes email \
    --region $REGION \
    --output json)

USER_POOL_ID=$(echo $USER_POOL_JSON | python -c "import sys,json; print(json.load(sys.stdin)['UserPool']['Id'])")
log "  User Pool ID: $USER_POOL_ID"

CLIENT_JSON=$(aws cognito-idp create-user-pool-client \
    --user-pool-id $USER_POOL_ID \
    --client-name hotel-booking-client \
    --no-generate-secret \
    --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH ALLOW_USER_SRP_AUTH \
    --region $REGION \
    --output json)

CLIENT_ID=$(echo $CLIENT_JSON | python -c "import sys,json; print(json.load(sys.stdin)['UserPoolClient']['ClientId'])")
log "  Client ID: $CLIENT_ID"

aws cognito-idp create-group --group-name ADMIN --user-pool-id $USER_POOL_ID --region $REGION 2>/dev/null || true
aws cognito-idp create-group --group-name USER --user-pool-id $USER_POOL_ID --region $REGION 2>/dev/null || true

COGNITO_ISSUER_URI="https://cognito-idp.${REGION}.amazonaws.com/${USER_POOL_ID}"

cat >> "$ENV_FILE" <<EOF
USER_POOL_ID=$USER_POOL_ID
CLIENT_ID=$CLIENT_ID
COGNITO_ISSUER_URI=$COGNITO_ISSUER_URI
EOF

###############################################################################
# 4. RDS PostgreSQL
###############################################################################
log "Creating RDS PostgreSQL instance (this takes ~5 minutes)..."
aws rds create-db-instance \
    --db-instance-identifier hoteldb \
    --db-instance-class db.t3.micro \
    --engine postgres \
    --engine-version 15.18 \
    --master-username $DB_USERNAME \
    --master-user-password "$DB_PASSWORD" \
    --allocated-storage 20 \
    --db-name $DB_NAME \
    --publicly-accessible \
    --no-multi-az \
    --backup-retention-period 0 \
    --region $REGION \
    --output json 2>/dev/null || log "RDS may already exist, continuing..."

log "Waiting for RDS to become available..."
aws rds wait db-instance-available --db-instance-identifier hoteldb --region $REGION

RDS_ENDPOINT=$(aws rds describe-db-instances \
    --db-instance-identifier hoteldb \
    --region $REGION \
    --query 'DBInstances[0].Endpoint.Address' \
    --output text)

RDS_URL="jdbc:postgresql://${RDS_ENDPOINT}:5432/${DB_NAME}"
log "  RDS Endpoint: $RDS_ENDPOINT"

cat >> "$ENV_FILE" <<EOF
RDS_ENDPOINT=$RDS_ENDPOINT
RDS_URL=$RDS_URL
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD
EOF

###############################################################################
# 5. ElastiCache Redis
###############################################################################
log "Creating ElastiCache Redis cluster..."
aws elasticache create-cache-cluster \
    --cache-cluster-id hotel-redis \
    --cache-node-type cache.t3.micro \
    --engine redis \
    --num-cache-nodes 1 \
    --region $REGION \
    --output json 2>/dev/null || log "Redis may already exist, continuing..."

log "Waiting for Redis cluster to be available..."
aws elasticache wait cache-cluster-available --cache-cluster-id hotel-redis --region $REGION

REDIS_ENDPOINT=$(aws elasticache describe-cache-clusters \
    --cache-cluster-id hotel-redis \
    --show-cache-node-info \
    --region $REGION \
    --query 'CacheClusters[0].CacheNodes[0].Endpoint.Address' \
    --output text)
log "  Redis Endpoint: $REDIS_ENDPOINT"

echo "REDIS_ENDPOINT=$REDIS_ENDPOINT" >> "$ENV_FILE"

###############################################################################
# 6. SQS Queue
###############################################################################
log "Creating SQS queue..."
SQS_JSON=$(aws sqs create-queue \
    --queue-name hotel-new-reservations \
    --region $REGION \
    --output json)

SQS_URL=$(echo $SQS_JSON | python -c "import sys,json; print(json.load(sys.stdin)['QueueUrl'])")
log "  SQS URL: $SQS_URL"
echo "SQS_URL=$SQS_URL" >> "$ENV_FILE"

###############################################################################
# 7. S3 Buckets
###############################################################################
log "Creating S3 buckets..."
FRONTEND_BUCKET="hotel-booking-frontend-${UNIQUE_SUFFIX}"
IMAGES_BUCKET="hotel-booking-images-${UNIQUE_SUFFIX}"

aws s3 mb "s3://$FRONTEND_BUCKET" --region $REGION 2>/dev/null || true
aws s3 mb "s3://$IMAGES_BUCKET" --region $REGION 2>/dev/null || true

# Configure static website hosting
aws s3 website "s3://$FRONTEND_BUCKET" --index-document index.html --error-document index.html

# Public read access for frontend bucket
aws s3api put-bucket-policy \
    --bucket $FRONTEND_BUCKET \
    --policy "{
        \"Version\": \"2012-10-17\",
        \"Statement\": [{
            \"Sid\": \"PublicReadGetObject\",
            \"Effect\": \"Allow\",
            \"Principal\": \"*\",
            \"Action\": \"s3:GetObject\",
            \"Resource\": \"arn:aws:s3:::${FRONTEND_BUCKET}/*\"
        }]
    }"

# Disable block public access for frontend bucket
aws s3api put-public-access-block \
    --bucket $FRONTEND_BUCKET \
    --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

cat >> "$ENV_FILE" <<EOF
FRONTEND_BUCKET=$FRONTEND_BUCKET
IMAGES_BUCKET=$IMAGES_BUCKET
EOF

###############################################################################
# 8. App Runner IAM Role
###############################################################################
log "Creating App Runner IAM role..."
APPRUNNER_ROLE_ARN=$(aws iam get-role --role-name AppRunnerECRAccessRole --query 'Role.Arn' --output text 2>/dev/null) || true

if [ -z "$APPRUNNER_ROLE_ARN" ] || [ "$APPRUNNER_ROLE_ARN" == "None" ]; then
    aws iam create-role \
        --role-name AppRunnerECRAccessRole \
        --assume-role-policy-document '{
            "Version":"2012-10-17",
            "Statement":[{
                "Effect":"Allow",
                "Principal":{"Service":"build.apprunner.amazonaws.com"},
                "Action":"sts:AssumeRole"
            }]
        }' 2>/dev/null || true

    aws iam attach-role-policy \
        --role-name AppRunnerECRAccessRole \
        --policy-arn arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess 2>/dev/null || true

    APPRUNNER_ROLE_ARN=$(aws iam get-role --role-name AppRunnerECRAccessRole --query 'Role.Arn' --output text)
fi
log "  App Runner Role ARN: $APPRUNNER_ROLE_ARN"
echo "APPRUNNER_ROLE_ARN=$APPRUNNER_ROLE_ARN" >> "$ENV_FILE"

###############################################################################
# Helper function to deploy App Runner service
###############################################################################
deploy_apprunner() {
    local SVC_NAME=$1
    local IMAGE=$2
    local PORT=$3
    local ENV_JSON=$4

    log "Deploying App Runner service: $SVC_NAME..."

    # Check if service already exists
    EXISTING=$(aws apprunner list-services --region $REGION \
        --query "ServiceSummaryList[?ServiceName=='$SVC_NAME'].ServiceArn" \
        --output text 2>/dev/null)

    if [ -n "$EXISTING" ]; then
        log "  Updating existing service: $SVC_NAME"
        aws apprunner update-service \
            --service-arn "$EXISTING" \
            --source-configuration "{
                \"ImageRepository\": {
                    \"ImageIdentifier\": \"$IMAGE\",
                    \"ImageRepositoryType\": \"ECR\",
                    \"ImageConfiguration\": {
                        \"Port\": \"$PORT\",
                        \"RuntimeEnvironmentVariables\": $ENV_JSON
                    }
                },
                \"AuthenticationConfiguration\": {
                    \"AccessRoleArn\": \"$APPRUNNER_ROLE_ARN\"
                }
            }" \
            --region $REGION --output json | python -c "import sys,json; d=json.load(sys.stdin); print('ARN:', d['Service']['ServiceArn'])"
    else
        RESULT=$(aws apprunner create-service \
            --service-name "$SVC_NAME" \
            --source-configuration "{
                \"ImageRepository\": {
                    \"ImageIdentifier\": \"$IMAGE\",
                    \"ImageRepositoryType\": \"ECR\",
                    \"ImageConfiguration\": {
                        \"Port\": \"$PORT\",
                        \"RuntimeEnvironmentVariables\": $ENV_JSON
                    }
                },
                \"AuthenticationConfiguration\": {
                    \"AccessRoleArn\": \"$APPRUNNER_ROLE_ARN\"
                },
                \"AutoDeploymentsEnabled\": false
            }" \
            --instance-configuration "{\"Cpu\": \"1 vCPU\", \"Memory\": \"2 GB\"}" \
            --region $REGION --output json)
        echo "$RESULT" | python -c "import sys,json; d=json.load(sys.stdin); print(d['Service']['ServiceUrl'])"
    fi
}

###############################################################################
# 9. Deploy App Runner Services
###############################################################################
log "Deploying microservices to App Runner..."

# hotel-service
HOTEL_ENV="{
    \"SPRING_DATASOURCE_URL\": \"$RDS_URL\",
    \"SPRING_DATASOURCE_USERNAME\": \"$DB_USERNAME\",
    \"SPRING_DATASOURCE_PASSWORD\": \"$DB_PASSWORD\",
    \"SPRING_REDIS_HOST\": \"$REDIS_ENDPOINT\",
    \"SPRING_REDIS_PORT\": \"6379\",
    \"AWS_SQS_QUEUE_URL\": \"$SQS_URL\",
    \"AWS_REGION\": \"$REGION\",
    \"AWS_COGNITO_ISSUER_URI\": \"$COGNITO_ISSUER_URI\",
    \"S3_BUCKET_NAME\": \"$IMAGES_BUCKET\"
}"

HOTEL_URL=$(deploy_apprunner "hotel-service" "$ECR_BASE/hotel-service:latest" "8080" "$HOTEL_ENV")
HOTEL_SERVICE_URL="https://$HOTEL_URL"
echo "HOTEL_SERVICE_URL=$HOTEL_SERVICE_URL" >> "$ENV_FILE"
log "  hotel-service URL: $HOTEL_SERVICE_URL"

# comments-service
COMMENTS_ENV="{
    \"SPRING_DATA_MONGODB_URI\": \"${SPRING_DATA_MONGODB_URI:?Error: SPRING_DATA_MONGODB_URI environment variable is not set}\",
    \"AWS_COGNITO_ISSUER_URI\": \"$COGNITO_ISSUER_URI\",
    \"AWS_REGION\": \"$REGION\"
}"
COMMENTS_URL=$(deploy_apprunner "comments-service" "$ECR_BASE/comments-service:latest" "8081" "$COMMENTS_ENV")
COMMENTS_SERVICE_URL="https://$COMMENTS_URL"
echo "COMMENTS_SERVICE_URL=$COMMENTS_SERVICE_URL" >> "$ENV_FILE"
log "  comments-service URL: $COMMENTS_SERVICE_URL"

# notification-service
NOTIFICATION_ENV="{
    \"HOTEL_SERVICE_BASE_URL\": \"$HOTEL_SERVICE_URL\",
    \"AWS_SQS_QUEUE_URL\": \"$SQS_URL\",
    \"AWS_REGION\": \"$REGION\",
    \"MAIL_HOST\": \"smtp.gmail.com\",
    \"MAIL_PORT\": \"587\",
    \"MAIL_USERNAME\": \"\",
    \"MAIL_PASSWORD\": \"\"
}"
NOTIFICATION_URL=$(deploy_apprunner "notification-service" "$ECR_BASE/notification-service:latest" "8082" "$NOTIFICATION_ENV")
NOTIFICATION_SERVICE_URL="https://$NOTIFICATION_URL"
echo "NOTIFICATION_SERVICE_URL=$NOTIFICATION_SERVICE_URL" >> "$ENV_FILE"
log "  notification-service URL: $NOTIFICATION_SERVICE_URL"

# ai-agent-service
AI_ENV="{
    \"PORT\": \"3000\",
    \"ANTHROPIC_API_KEY\": \"$ANTHROPIC_API_KEY\",
    \"HOTEL_SERVICE_URL\": \"$HOTEL_SERVICE_URL\",
    \"AWS_COGNITO_ISSUER_URI\": \"$COGNITO_ISSUER_URI\",
    \"AWS_REGION\": \"$REGION\"
}"
AI_URL=$(deploy_apprunner "ai-agent-service" "$ECR_BASE/ai-agent-service:latest" "3000" "$AI_ENV")
AI_SERVICE_URL="https://$AI_URL"
echo "AI_SERVICE_URL=$AI_SERVICE_URL" >> "$ENV_FILE"
log "  ai-agent-service URL: $AI_SERVICE_URL"

# api-gateway
GATEWAY_ENV="{
    \"HOTEL_SERVICE_URL\": \"$HOTEL_SERVICE_URL\",
    \"AI_AGENT_SERVICE_URL\": \"$AI_SERVICE_URL\",
    \"COMMENTS_SERVICE_URL\": \"$COMMENTS_SERVICE_URL\",
    \"NOTIFICATION_SERVICE_URL\": \"$NOTIFICATION_SERVICE_URL\",
    \"AWS_COGNITO_ISSUER_URI\": \"$COGNITO_ISSUER_URI\",
    \"AWS_REGION\": \"$REGION\"
}"
GATEWAY_URL=$(deploy_apprunner "api-gateway" "$ECR_BASE/api-gateway:latest" "8080" "$GATEWAY_ENV")
GATEWAY_SERVICE_URL="https://$GATEWAY_URL"
echo "GATEWAY_SERVICE_URL=$GATEWAY_SERVICE_URL" >> "$ENV_FILE"
log "  api-gateway URL: $GATEWAY_SERVICE_URL"

###############################################################################
# 10. Build and Deploy Frontend (using Docker build)
###############################################################################
log "Building frontend..."
FRONTEND_DIR="$SCRIPT_DIR/frontend"

cat > "$FRONTEND_DIR/.env" <<EOF
VITE_API_GATEWAY_URL=$GATEWAY_SERVICE_URL
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
VITE_AWS_REGION=$REGION
EOF

# Build frontend image
log "Building frontend Docker image..."
docker build -t frontend-build:latest "$FRONTEND_DIR" --platform linux/amd64

# Extract built files from nginx image
TEMP_DIST=$(mktemp -d 2>/dev/null || mkdir -p /tmp/frontend-dist-$$ && echo /tmp/frontend-dist-$$)
CONTAINER_ID=$(docker create frontend-build:latest)
docker cp "$CONTAINER_ID:/usr/share/nginx/html/." "$TEMP_DIST/"
docker rm "$CONTAINER_ID"

log "Uploading frontend to S3..."
aws s3 sync "$TEMP_DIST/" "s3://$FRONTEND_BUCKET" --region $REGION --delete
rm -rf "$TEMP_DIST"

# Also push to ECR for reference
docker tag frontend-build:latest "$ECR_BASE/frontend:latest"
docker push "$ECR_BASE/frontend:latest" 2>/dev/null || true

###############################################################################
# 11. CloudFront Distribution
###############################################################################
log "Creating CloudFront distribution..."
CF_JSON=$(aws cloudfront create-distribution \
    --origin-domain-name "${FRONTEND_BUCKET}.s3-website.${REGION}.amazonaws.com" \
    --default-root-object index.html \
    --output json 2>/dev/null) || CF_JSON=""

if [ -n "$CF_JSON" ]; then
    CF_DOMAIN=$(echo $CF_JSON | python -c "import sys,json; print(json.load(sys.stdin)['Distribution']['DomainName'])")
    CF_ID=$(echo $CF_JSON | python -c "import sys,json; print(json.load(sys.stdin)['Distribution']['Id'])")
    log "  CloudFront domain: $CF_DOMAIN"
    cat >> "$ENV_FILE" <<EOF
CLOUDFRONT_DOMAIN=$CF_DOMAIN
CLOUDFRONT_ID=$CF_ID
FRONTEND_URL=https://$CF_DOMAIN
EOF
fi

###############################################################################
# 12. EventBridge Scheduler for Nightly Job
###############################################################################
log "Creating EventBridge Scheduler for nightly job..."

# Create IAM role for EventBridge to invoke HTTP
SCHEDULER_ROLE=$(aws iam get-role --role-name EventBridgeSchedulerRole --query 'Role.Arn' --output text 2>/dev/null) || true
if [ -z "$SCHEDULER_ROLE" ] || [ "$SCHEDULER_ROLE" == "None" ]; then
    aws iam create-role \
        --role-name EventBridgeSchedulerRole \
        --assume-role-policy-document '{
            "Version":"2012-10-17",
            "Statement":[{
                "Effect":"Allow",
                "Principal":{"Service":"scheduler.amazonaws.com"},
                "Action":"sts:AssumeRole"
            }]
        }' 2>/dev/null || true

    aws iam attach-role-policy \
        --role-name EventBridgeSchedulerRole \
        --policy-arn arn:aws:iam::aws:policy/AmazonEventBridgeSchedulerFullAccess 2>/dev/null || true

    SCHEDULER_ROLE=$(aws iam get-role --role-name EventBridgeSchedulerRole --query 'Role.Arn' --output text)
fi

# Note: EventBridge Scheduler for HTTP targets requires a Lambda or Step Functions intermediary.
# For simplicity, we document this as a manual step or use the notification service's /nightly endpoint.
log "  NOTE: Configure EventBridge to POST to $NOTIFICATION_SERVICE_URL/api/v1/notifications/nightly at cron(0 2 * * ? *)"
echo "NIGHTLY_JOB_ENDPOINT=$NOTIFICATION_SERVICE_URL/api/v1/notifications/nightly" >> "$ENV_FILE"

###############################################################################
# Summary
###############################################################################
log ""
log "============================================================"
log "DEPLOYMENT COMPLETE!"
log "============================================================"
log ""
log "Generated values saved to: $ENV_FILE"
log ""
log "Service URLs:"
log "  API Gateway:          $GATEWAY_SERVICE_URL"
log "  Hotel Service:        $HOTEL_SERVICE_URL"
log "  Comments Service:     $COMMENTS_SERVICE_URL"
log "  Notification Service: $NOTIFICATION_SERVICE_URL"
log "  AI Agent Service:     $AI_SERVICE_URL"
log "  Frontend (S3):        http://$FRONTEND_BUCKET.s3-website.$REGION.amazonaws.com"
if [ -n "$CF_DOMAIN" ]; then
    log "  Frontend (CloudFront): https://$CF_DOMAIN"
fi
log ""
log "Cognito:"
log "  User Pool ID: $USER_POOL_ID"
log "  Client ID:    $CLIENT_ID"
log ""
log "Swagger UIs:"
log "  Hotel Service:        $HOTEL_SERVICE_URL/swagger-ui/index.html"
log "  Comments Service:     $COMMENTS_SERVICE_URL/swagger-ui/index.html"
log "  Notification Service: $NOTIFICATION_SERVICE_URL/swagger-ui/index.html"
log "  AI Agent Service:     $AI_SERVICE_URL/api-docs"
log ""
